language: php

php:
  - 5.2
  - 5.3
  #- 5.4

env:
  - OMEKA_BRANCH=stable-1.5
  #- OMEKA_BRANCH=master

before_script:
  - bundle install
  - ./.travis.setup.sh
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

script: ./.travis.tests.sh

notifications:
  irc: "irc.freenode.org#slab"
